[package]
name = "my_project"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
config = "0.14.0"
serde_json = "1.0"
reqwest = "0.12.5"
futures = "0.3.30"
