authorization: "Bearer <your_token>"
accept: "application/json, text/plain, */*"
accept_language: "en-US,en;q=0.9,ja;q=0.8"
connection: "keep-alive"
content_length: "0"
# origin: "<your_origin>"
# referer: "<your_referer>"
sec_fetch_dest: "empty"
sec_fetch_mode: "cors"
sec_fetch_site: "same-site"
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
sec_ch_ua: "\"Not/A)Brand\";v=\"8\", \"Chromium\";v=\"126\", \"Google Chrome\";v=\"126\""
sec_ch_ua_mobile: "?0"
sec_ch_ua_platform: "\"Windows\""
